adjetivo = [
"genio",
"hacker",
"de Ojojona",
"en riesgo social",
"genio de la computacion",
"genio de la robótica",
"grande de la tecnología en Centroamérica",
"estudiante de excelencia académica",
"promesa de Honduras",
"imperdible",
"espectacular",
"tremenda",
"experto",
"candente",
"de lujo",
"picante",
"sagaz",
"perspicaz",
"audaz",
"imbuído de astucia",
"de fama en los barrios bajas",
"filtra información de",
"de bajos recursos económicos",
"despampanante",
"master en radimparencia",
"entrepreneur",
"gurú de la informática",
"mago de las finanzas",
"gigante de el análisis científico"];
