adjetivo = [
"genio",
"teme que",
"deslumbrante"
"sampedrano",
"que",
"grafiterista",
"radical",
"hacker",
"de UNAH-VS",
"de minorías",
"dentro de comunidad latina",
"de Ojojona",
"irreverente",
"del gremio transportista",
"en el extranjero",
"en condiciones adversas",
"en menosprecio",
"Einstein",
"Einstein de los negocios",
"del siglo XXI",
"de aldea marginal",
"en riesgo social",
"asesor de reconocida trayectoria",
"autodidacta",
"genio de la computacion",
"genio de la robótica",
"grande de la tecnología en Centroamérica",
"de excelencia académica",
"promesa de Honduras",
"espectacular",
"de habilidad inigualable",
"experto",
"de lujo",
"autodidacta",
"sagaz",
"perspicaz",
"audaz",
"excepcional",
"desbordante de astucia",
"de fama en los barrios bajos",
"de bajos recursos económicos",
"master en radimparencia",
"entrepreneur",
"emprendedor",
"gurú de la informática",
"mago de las finanzas",
"del interior",
"gigante de el análisis científico"];
