adjetivo = [
"genio",
"hacker",
"de UNAH-VS",
"de Ojojona",
"irreverente",
"del IHSS",
"del siglo XXI",
"de aldea marginal",
"en riesgo social",
"asesor de reconocida trayectoria",
"autodidacta",
"genio de la computacion",
"genio de la robótica",
"grande de la tecnología en Centroamérica",
"de excelencia académica",
"promesa de Honduras",
"imperdible",
"espectacular",
"de habilidad inigualable",
"experto",
"de lujo",
"autodidacta",
"sagaz",
"perspicaz",
"audaz",
"excepcional",
"desbordante de astucia",
"de fama en los barrios bajos",
"de bajos recursos económicos",
"master en radimparencia",
"entrepreneur",
"gurú de la informática",
"mago de las finanzas",
"gigante de el análisis científico"];
