complemento = [
"el mundo",
"el nuevo Facebook",
"idea millonaria",
"el éxito",
"la cura del cancer",
"Silicon Valley de Latinoamérica",
"máquina de educación para los más desfavorecidos",
"foros internacionales de convergencia",
"escuela de potenciación de habilidades para las zonas rurales",
"picante método de crear dinero",
"startup del futuro hoy",
"polémica tecnología",
"futuro brillante en el presente",
"solución al hambre para los países del tercer mundo"];
