complemento = [
"el mundo",
"el nuevo Facebook",
"avance descomunal para la ciencia moderna",
"sueño de realidad virtual",
"idea millonaria",
"computadoras cuánticas",
"coyontura de apps móviles",
"Uber de Guamilito",
"implementación de filosofía",
"teorema del gato de Schroedinger",
"reforma a los sistemas de gobierno",
"marca de Instagram",
"máquina que desimprime el toner de las hojas de papel",
"planta nuclear",
"lanzadera espacial en suelo patrio",
"algoritmo de búsqueda Google",
"nuevo mercado de Microsoft en órbita baja de la tierra",
"medios de comunicación masiva de Siria",
"el éxito",
"historia de el indio Lempira",
"ecología del planeta",
"pronóstico de calentamiento global",
"La Dubai del tercer mundo",
"la cura del cancer",
"la grecia de región hispánica",
"seguridad en productividad de sectores peligrosos del interior",
"cumbre de comercio internacional",
"solución para ayuda de invidentes",
"Silicon Valley de Latinoamérica",
"máquina de educación para los más desfavorecidos",
"tecnología 3D para crear prótesis en universidad estadounidense",
"foros internacionales de convergencia",
"escuela de potenciación agrícola para zonas rurales",
"picante método de crear dinero",
"startup del mañana, hoy",
"polémica tecnología",
"hilarante trastorno compulsivo",
"cosplay",
"empresas emergentes",
"nueva bolsa de valores",
"tradiciones autóctonas de Honduras",
"antiguo remedio contra la diabetes",
"solución al hambre para los países del tercer mundo"];
