complemento = [
"el mundo",
"el nuevo Facebook",
"idea millonaria",
"medios de comunicación masiva de Siria",
"el éxito",
"La Dubai del tercer mundo",
"la cura del cancer",
"la grecia de región hispánica",
"seguridad en productividad de sectores peligrosos del interior",
"solución para ayuda de invidentes",
"Silicon Valley de Latinoamérica",
"máquina de educación para los más desfavorecidos",
"tecnología 3D para crear prótesis en universidad estadounidense",
"foros internacionales de convergencia",
"escuela de potenciación de habilidades para las zonas rurales",
"picante método de crear dinero",
"startup del mañana, hoy",
"polémica tecnología",
"futuro brillante en el presente",
"nueva bolsa de valores",
"tradiciones autóctonas de Honduras",
"antiguo remedio contra la diabetes",
"solución al hambre para los países del tercer mundo"];
