verbo = [
"crea",
"inventa",
"reinventa",
"obtiene",
"revoluciona",
"desarrolla",
"arremete contra",
"explotó",
"desmiente",
"propone",
"reimagina",
"innova",
"se consagra por",
"disrupciona el mercado de",
"masacró",
"le pone sabor latino",
"hace histórica hazaña en",
"logra"];
